---
permalink: sm-storage/functional-comparison-of-pools-and-volume-groups.html 
sidebar: sidebar 
keywords: function, purpose, pool, volume, group, same, objects, set, drives, logically, together, storage, array, create, host, access 
summary: 集區和磁碟區群組的功能和用途相同。這兩個物件都是儲存陣列中邏輯分組的一組磁碟機、用於建立主機可以存取的磁碟區。 
---
= 集區和Volume群組的功能比較
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
集區和磁碟區群組的功能和用途相同。這兩個物件都是儲存陣列中邏輯分組的一組磁碟機、用於建立主機可以存取的磁碟區。

下表可協助您決定集區或磁碟區群組是否最符合您的儲存需求。

[cols="3*""]
|===
| 功能 | 資源池 | Volume群組 


 a| 
支援不同的RAID層級
 a| 
不可以永遠使用RAID 6。
 a| 
是的。提供RAID 0、1、10、5和6。



 a| 
支援的精簡磁碟區
 a| 
是的
 a| 
否



 a| 
支援完整磁碟加密（FDE）
 a| 
是的
 a| 
是的



 a| 
支援資料保證（DA）
 a| 
是的
 a| 
是的



 a| 
支援機櫃遺失保護
 a| 
是的
 a| 
是的



 a| 
支援藥櫃遺失保護
 a| 
是的
 a| 
是的



 a| 
支援混合式磁碟機速度
 a| 
建議相同、但不需要。最慢的磁碟機決定所有磁碟機的速度。
 a| 
建議相同、但不需要。最慢的磁碟機決定所有磁碟機的速度。



 a| 
支援混合式磁碟機容量
 a| 
建議相同、但不需要。最小磁碟機決定所有磁碟機的容量。
 a| 
建議相同、但不需要。最小磁碟機決定所有磁碟機的容量。



 a| 
最小磁碟機數量
 a| 
11.
 a| 
取決於RAID層級。RAID 0需要1。RAID 1或10需要2（需要偶數）。RAID 5最低為3。RAID 6最低為5。



 a| 
最大磁碟機數量
 a| 
儲存陣列的上限
 a| 
RAID 1和10 -最高可達儲存陣列RAID 5、6-30磁碟機的上限



 a| 
可在建立磁碟區時選擇個別磁碟機
 a| 
否
 a| 
是的



 a| 
可在建立Volume時指定區段大小
 a| 
是的。支援12K。
 a| 
是的



 a| 
可在建立磁碟區時指定I/O特性
 a| 
否
 a| 
是的。支援檔案系統、資料庫、多媒體和自訂。



 a| 
磁碟機故障保護
 a| 
使用資源池中每個磁碟機的保留容量、加快重建速度。
 a| 
使用熱備援磁碟機。重建受限於磁碟機的IOPs。



 a| 
達到容量限制時發出警告
 a| 
是的。可在使用容量達到最大容量百分比時設定警示。
 a| 
否



 a| 
移轉至支援的不同儲存陣列
 a| 
不可以需要先移轉至磁碟區群組。
 a| 
是的



 a| 
動態區段大小（DSS）
 a| 
否
 a| 
是的



 a| 
可以變更RAID層級
 a| 
否
 a| 
是的



 a| 
Volume擴充（增加容量）
 a| 
是的
 a| 
是的



 a| 
容量擴充（新增容量）
 a| 
是的
 a| 
是的



 a| 
容量減量
 a| 
是的
 a| 
否

|===
[NOTE]
====
集區或磁碟區群組不支援混合式磁碟機類型（HDD、SSD）。

====