---
settings:
  name: SANtricity 11.6
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: 軟件SANtricity
    url: "/e-series-santricity-116"
    version-number: '11.6'
  - name: 軟件SANtricity
    url: "/e-series-santricity"
    version-number: '11.8'
  - name: 軟件SANtricity
    url: "/e-series-santricity-117"
    version-number: '11.7'
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 統一文檔SANtricity
    url: "/index.html"
  - title: 系統管理員
    entries:
    - section: sm-interface
    - section: sm-storage
    - section: sm-mirroring
    - section: sm-hardware
    - section: sm-settings
    - section: sm-support
  - title: Unified Manager
    entries:
    - section: um-admin
    - section: um-manage
    - section: um-certificates
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: E-Series
  repo: e-series-family
