---
permalink: sm-interface/setup-wizard-terminology.html 
sidebar: sidebar 
keywords: setup, wizard, apply, storage, array 
summary: 瞭解安裝精靈條款如何套用至您的儲存陣列。 
---
= 設定精靈術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解安裝精靈條款如何套用至您的儲存陣列。

[cols="1a,3a"]
|===
| 期限 | 說明 


 a| 
應用程式
 a| 
應用程式是軟體程式、例如Microsoft SQL Server或Microsoft Exchange。



 a| 
警示
 a| 
警示會通知系統管理員儲存陣列上發生的重要事件。警示可透過電子郵件、SNMP設陷或系統記錄傳送。



 a| 
AutoSupport
 a| 
此功能可監控儲存陣列的健全狀況、並將自動派單傳送給技術支援部門。AutoSupport



 a| 
硬體
 a| 
儲存系統硬體包括儲存陣列、控制器和磁碟機。



 a| 
主機
 a| 
主機是一種伺服器、可將I/O傳送至儲存陣列上的磁碟區。



 a| 
物件
 a| 
物件是任何邏輯或實體儲存元件。邏輯物件包括磁碟區群組、集區和磁碟區。實體物件包括儲存陣列、陣列控制器、主機和磁碟機。



 a| 
資源池
 a| 
資源池是邏輯分組的一組磁碟機。您可以使用集區來建立一個或多個可供主機存取的磁碟區。（您可以從集區或磁碟區群組建立磁碟區。）



 a| 
Volume
 a| 
Volume是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機所建立的邏輯元件、可用來存取儲存陣列上的儲存設備。

磁碟區是從集區或磁碟區群組中可用的容量所建立。磁碟區具有已定義的容量。雖然磁碟區可能包含多個磁碟機、但磁碟區會顯示為主機的一個邏輯元件。



 a| 
Volume群組
 a| 
Volume群組是具有共享特性之磁碟區的容器。Volume群組具有已定義的容量和RAID層級。您可以使用Volume群組來建立一個或多個可讓主機存取的磁碟區。（您可以從磁碟區群組或集區建立磁碟區。）



 a| 
工作負載
 a| 
工作負載是支援應用程式的儲存物件。您可以針對每個應用程式定義一或多個工作負載或執行個體。對於某些應用程式、System Manager會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。例如、如果您建立支援Microsoft SQL Server應用程式的工作負載、然後為該工作負載建立磁碟區、則基礎磁碟區特性會最佳化以支援Microsoft SQL Server。

|===