---
permalink: sm-hardware/controller-terminology.html 
sidebar: sidebar 
keywords: controller, terms, storage, array 
summary: 瞭解控制器術語如何適用於您的儲存陣列。 
---
= 控制器術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解控制器術語如何適用於您的儲存陣列。

[cols="1a,3a"]
|===
| 元件 | 說明 


 a| 
控制器
 a| 
控制器由主機板、韌體和軟體組成。它控制磁碟機並實作System Manager功能。



 a| 
控制器機櫃
 a| 
控制器機櫃包含一組磁碟機和一或多個控制器容器。控制器容器可容納控制器、主機介面卡（HIC）和電池。



 a| 
DHCP
 a| 
動態主機組態傳輸協定（DHCP）是一種用於網際網路傳輸協定（IP）網路的傳輸協定、可用來動態分配網路組態參數、例如IP位址。



 a| 
DNS
 a| 
網域名稱系統（DNS）是連線至網際網路或私有網路之裝置的命名系統。DNS伺服器會維護網域名稱目錄、並將其轉譯為網際網路傳輸協定（IP）位址。



 a| 
雙工組態
 a| 
雙工是儲存陣列內的雙控制器模組組組態。雙工系統在控制器、邏輯磁碟區路徑和磁碟路徑方面具有完全備援的功能。如果一個控制器故障、另一個控制器就會接管其I/O、以維持可用度。雙工系統也有備援風扇和電源供應器。



 a| 
全雙工/半雙工連線
 a| 
全雙工和半雙工是指連線模式。在全雙工模式中、兩個裝置可以同時雙向通訊。在半雙工模式中、裝置一次可以單向通訊（一部裝置會傳送訊息、另一部裝置則會接收訊息）。



 a| 
HIC
 a| 
主機介面卡（HIC）可選擇性安裝在控制器容器內。控制器內建的主機連接埠稱為基板主機連接埠。HIC內建的主機連接埠稱為HIC連接埠。



 a| 
ICMP Ping回應
 a| 
網際網路控制訊息傳輸協定（ICMP）是網路電腦的作業系統用來傳送訊息的傳輸協定。ICMP訊息會判斷主機是否可連線、以及從該主機取得封包所需的時間。



 a| 
MAC位址
 a| 
乙太網路使用媒體存取控制識別碼（MAC位址）來區分連接同一個實體傳輸網路介面上兩個連接埠的獨立邏輯通道。



 a| 
管理用戶端
 a| 
管理用戶端是指安裝瀏覽器以存取System Manager的電腦。



 a| 
MTU
 a| 
最大傳輸單元（MTU）是可在網路中傳送的最大封包或框架。



 a| 
NTP
 a| 
網路時間傳輸協定（NTP）是一種網路傳輸協定、可在資料網路中的電腦系統之間進行時鐘同步。



 a| 
單工組態
 a| 
單工是儲存陣列內的單一控制器模組組組態。單工系統不提供控制器或磁碟路徑備援、但有備援風扇和電源供應器。



 a| 
VLAN
 a| 
虛擬區域網路（VLAN）是一種邏輯網路、其運作方式類似於實體獨立於其他受相同裝置（交換器、路由器等）支援的網路。

|===