---
permalink: sm-hardware/drive-terminology.html 
sidebar: sidebar 
keywords: drive, apply, storage array 
summary: 瞭解磁碟機條款如何適用於您的儲存陣列。 
---
= 推動術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解磁碟機條款如何適用於您的儲存陣列。

[cols="1a,3a"]
|===
| 元件 | 說明 


 a| 
大
 a| 
資料保證（DA）是一項功能、可檢查及修正資料經由控制器向下傳輸至磁碟機時可能發生的錯誤。資料保證功能可在集區或磁碟區群組層級啟用、主機可使用具有DA功能的I/O介面、例如Fibre Channel。



 a| 
磁碟機安全功能
 a| 
磁碟機安全性是一項儲存陣列功能、可透過全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機提供額外的安全層級。當這些磁碟機搭配磁碟機安全功能使用時、它們需要安全金鑰才能存取其資料。當磁碟機從陣列中實際移除時、除非安裝在另一個陣列中、否則無法運作、此時磁碟機將處於「安全性鎖定」狀態、直到提供正確的安全金鑰為止。



 a| 
磁碟機櫃
 a| 
磁碟機櫃也稱為擴充櫃、包含一組磁碟機和兩個輸入/輸出模組（IOM）。IOM包含SAS連接埠、可將磁碟機櫃連接至控制器機櫃或其他磁碟機櫃。



 a| 
DULBE
 a| 
取消分配或未寫入的邏輯區塊錯誤（DULBE）是NVMe磁碟機的選項、可讓儲存陣列取消分配屬於磁碟區一部分的區塊。在磁碟機上取消分配區塊、可大幅縮短初始化磁碟區所需的時間。此外、主機可以使用NVMe資料集管理命令取消分配磁碟區中的邏輯區塊。



 a| 
FDE磁碟機
 a| 
全磁碟加密（FDE）磁碟機在硬體層級對磁碟機執行加密。硬碟內含ASIC晶片、可在寫入期間加密資料、然後在讀取期間解密資料。



 a| 
FIPS磁碟機
 a| 
FIPS磁碟機使用聯邦資訊處理標準（FIPS）140-2第2級。它們基本上是FDE磁碟機、符合美國政府的標準、以確保強大的加密演算法和方法。FIPS磁碟機的安全性標準高於FDE磁碟機。



 a| 
HDD
 a| 
硬碟機（HDD）是資料儲存設備、使用具有磁性塗層的旋轉式金屬盤片。



 a| 
熱備援磁碟機
 a| 
熱備援磁碟機在RAID 1、RAID 5或RAID 6磁碟區群組中扮演待命磁碟機的角色。它們是功能完整的磁碟機、不含任何資料。如果磁碟機在Volume群組中故障、控制器會自動將故障磁碟機的資料重新建構至熱備援磁碟機。



 a| 
NVMe
 a| 
非揮發性記憶體Express（NVMe）是專為Flash型儲存裝置（例如SSD磁碟機）所設計的介面。NVMe可降低I/O負荷、並與先前的邏輯裝置介面相比、提升效能。



 a| 
SAS
 a| 
序列附加SCSI（SAS）是一種點對點序列傳輸協定、可將控制器直接連結至磁碟機。



 a| 
具備安全功能的磁碟機
 a| 
可安全使用的磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機、在讀取期間加密資料並解密資料。這些磁碟機被視為安全的磁碟機、因為它們可以使用磁碟機安全功能來提高安全性。如果已針對這些磁碟機所使用的磁碟區群組和集區啟用「磁碟機安全性」功能、磁碟機就會變成安全的-_enabled_.



 a| 
啟用安全功能的磁碟機
 a| 
啟用安全功能的磁碟機可搭配磁碟機安全功能使用。當您啟用「磁碟機安全性」功能、然後將「磁碟機安全性」套用至安全的磁碟機上的集區或磁碟區群組時、磁碟機就會變成安全的__已啟用__。讀寫存取只能透過設定正確安全金鑰的控制器來使用。這項新增的安全功能可防止未獲授權存取從儲存陣列實體移除之磁碟機上的資料。



 a| 
SSD
 a| 
固態磁碟（SSD）是使用固態記憶體（Flash）持續儲存資料的資料儲存裝置。SSD可模擬傳統硬碟機、並與硬碟機使用的介面相同。

|===