---
permalink: sm-hardware/erase-drive.html 
sidebar: sidebar 
keywords: erase, secure, enabled, drive, reuse, volume, group, pool, ssd cache, storage array 
summary: 您可以清除啟用安全功能的磁碟機、以便在其他磁碟區群組、集區、SSD快取或其他儲存陣列中重複使用。此程序會重設磁碟機的安全性屬性、並確保無法再次讀取資料。 
---
= 清除啟用安全功能的磁碟機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以清除啟用安全功能的磁碟機、以便在其他磁碟區群組、集區、SSD快取或其他儲存陣列中重複使用。此程序會重設磁碟機的安全性屬性、並確保無法再次讀取資料。

啟用安全功能的磁碟機必須處於「未指派」狀態。

僅當您想要移除啟用安全功能的磁碟機上的所有資料、並重設磁碟機的安全屬性時、才可使用「安全清除」選項。

[CAUTION]
====
*可能的資料遺失*-安全清除作業無法復原。請務必在程序期間選取正確的磁碟機。

====
.步驟
. 選取*硬體*。
. 如果圖形顯示控制器、請按一下*顯示機櫃正面*。
+
圖形會變更、以顯示磁碟機而非控制器。

. 使用篩選欄位可檢視機櫃中所有已啟用安全功能且未指派磁碟機的資料。從*顯示磁碟機為...*下拉式清單中、選取*啟用安全保護*和*未指派*。
+
[NOTE]
====
如果所有磁碟機共用相同的實體屬性、則不會顯示*顯示磁碟機為...*篩選欄位。如果所有磁碟機都共用相同的邏輯屬性、則不會出現「* Anywhere in the storage array* filter」（*儲存陣列*篩選器的任何位置）欄位。

機櫃檢視僅顯示已啟用安全功能、未指派磁碟機；其他所有磁碟機則呈現灰色。

====
. 選取您要清除的安全磁碟機。
+
[CAUTION]
====
*可能會遺失資料*-請確定您已選取正確的磁碟機。完成「安全清除」作業之後、您將無法恢復任何資料。

====
+
隨即開啟磁碟機的內容功能表。

. 選擇*安全清除*。
+
只有當您選取未指派、啟用安全功能的磁碟機時、才會顯示「安全清除」選項。

+
[NOTE]
====
對於NVMe SED磁碟機、您必須提供PSID。您可以在磁碟機標籤上找到PSID。如果您沒有備份鎖定金鑰、就必須這麼做。

====
. 在安全清除磁碟機對話方塊中、閱讀有關資料遺失的重要資訊。
. 確認操作、然後按一下*清除*。


磁碟機現在可用於其他磁碟區群組或磁碟集區、或其他儲存陣列。
