---
permalink: sm-settings/configure-snmp-alerts.html 
sidebar: sidebar 
keywords: configuration, snmp alerts, identification, one server, storage array, snmp traps, community name, ip address 
summary: 若要設定簡單網路管理傳輸協定（SNMP）警示、您必須至少識別一部伺服器、讓儲存陣列的事件監視器能夠傳送SNMP設陷。此組態需要伺服器的社群名稱和IP位址。 
---
= 設定SNMP警示的社群和目的地
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要設定簡單網路管理傳輸協定（SNMP）警示、您必須至少識別一部伺服器、讓儲存陣列的事件監控器能夠傳送SNMP設陷。此組態需要伺服器的社群名稱和IP位址。

.開始之前
* 網路伺服器必須設定SNMP服務應用程式。您需要此伺服器的網路位址（無論是IPv4或IPv6位址）、事件監控器才能將陷阱訊息傳送到該位址。您可以使用多部伺服器（最多允許10部伺服器）。
* 必須建立社群名稱、僅包含可列印的Ascii字元。社群名稱是類似網路伺服器密碼的字串、通常由網路管理員建立。最多可建立256個社群。
* 管理資訊庫（mib）檔案已複製並使用SNMP服務應用程式在伺服器上編譯。此mib檔案定義要監控和管理的資料。
+
如果您沒有mib檔案、可以從NetApp支援網站取得：

+
** 前往 https://mysupport.netapp.com/site/["NetApp支援"^]。
** 單擊* Downloads *（下載*）。
** 按一下*軟體*。
** 找SANtricity 到您的管理軟體（例如、《Sf2系統管理程式》）、然後按一下右側的「* Go！*（執行！*）」。
** 按一下最新版本上的「*檢視與下載*」。
** 按一下頁面底部的*繼續*。
** 接受EULA。
** 向下捲動直到看到* SNMP陷阱的mib檔案*、然後按一下連結下載檔案。




.關於這項工作
本工作說明如何識別SNMP伺服器的設陷目的地、然後測試您的組態。

.步驟
. 選取*功能表：設定[警示]*。
. 選取「* SNMP *」索引標籤。
+
如果尚未設定社群、SNMP索引標籤會顯示「Configure Communities」（設定社群）。

. 選擇*設定社群*。
+
「*組態社群*」對話方塊隨即開啟。

. 在「*社群名稱*」欄位中、輸入網路伺服器的一或多個社群字串、然後按一下「*儲存*」。
+
「警示」頁面會顯示「新增設陷目的地」。

. 選取*新增設陷目的地*。
+
「*新增設陷目的地*」對話方塊隨即開啟。

. 輸入一個或多個陷阱目的地、選取其相關的社群名稱、然後按一下*「Add*（新增*）」。
+
** *陷阱目的地*-輸入執行SNMP服務之伺服器的IPV4或IPv6位址。
** *社群名稱*-從下拉式清單中、選取此設陷目的地的社群名稱。（如果您只定義一個社群名稱、該名稱就會出現在此欄位中。）
** *傳送驗證失敗Trap *-如果您想要在SNMP要求因為無法辨識的社群名稱而遭拒時、發出警示陷阱目的地、請選取此選項（核取方塊）。按一下「*新增*」之後、陷阱目的地和相關的社群名稱會出現在「*警示*」頁面的「* SNMP *」索引標籤中。


. 若要確定設陷有效、請從表格中選取設陷目的地、然後按一下*測試設陷目的地*、將測試設陷傳送到設定的位址。


.結果
每當發生警示事件時、事件監視器會將SNMP設陷傳送至伺服器。
