---
permalink: sm-settings/nvme-terminology.html 
sidebar: sidebar 
keywords: nvme, terms, storage array 
summary: 瞭解NVMe術語如何適用於您的儲存陣列。 
---
= NVMe術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解NVMe術語如何適用於您的儲存陣列。

[cols="1a,3a"]
|===
| 期限 | 說明 


 a| 
InfiniBand
 a| 
InfiniBand（IB）是高效能伺服器與儲存系統之間資料傳輸的通訊標準。



 a| 
命名空間
 a| 
命名空間是NVM儲存設備、其格式化為區塊存取。它類似於SCSI中的邏輯單元、與儲存陣列中的磁碟區相關。



 a| 
命名空間ID
 a| 
命名空間ID是NVMe控制器的命名空間唯一識別碼、可設定為1到255之間的值。它類似於SCSI中的邏輯單元號碼（LUN）。



 a| 
NQN
 a| 
NVMe合格名稱（NQN）用於識別遠端儲存目標（儲存陣列）。



 a| 
NVM
 a| 
非揮發性記憶體（NVM）是許多儲存設備類型所使用的持續記憶體。



 a| 
NVMe
 a| 
非揮發性記憶體Express（NVMe）是專為Flash型儲存裝置（例如SSD磁碟機）所設計的介面。NVMe可降低I/O負荷、並與先前的邏輯裝置介面相比、提升效能。



 a| 
NVMe
 a| 
非揮發性記憶體Express over Fabrics（NVMe）是一種規格、可讓NVMe命令和資料在主機與儲存設備之間透過網路傳輸。



 a| 
NVMe控制器
 a| 
NVMe控制器是在主機連線程序期間建立的。它提供主機與儲存陣列中命名空間之間的存取路徑。



 a| 
NVMe佇列
 a| 
佇列用於透過NVMe介面傳遞命令和訊息。



 a| 
NVMe子系統
 a| 
採用NVMe主機連線的儲存陣列。



 a| 
RDMA
 a| 
遠端直接記憶體存取（RDMA）可在網路介面卡（NIC）硬體中實作傳輸傳輸協定、讓資料更直接地進出伺服器。



 a| 
RoCE
 a| 
RDMA over Converged Ethernet（RoCE）是一種網路傳輸協定、可透過乙太網路進行遠端直接記憶體存取（RDMA）。



 a| 
SSD
 a| 
固態磁碟（SSD）是使用固態記憶體（Flash）持續儲存資料的資料儲存裝置。SSD可模擬傳統硬碟機、並與硬碟機使用的介面相同。

|===