---
permalink: sm-settings/unlock-drives-using-an-internal-security-key.html 
sidebar: sidebar 
keywords: secure, enable, storage array, appropriate, importing, new storage, drive 
summary: 如果您將啟用安全功能的磁碟機從一個儲存陣列移至另一個儲存陣列、則必須將適當的安全金鑰匯入新的儲存陣列。匯入金鑰會解除鎖定磁碟機上的資料。 
---
= 使用安全金鑰解除磁碟機鎖定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您將啟用安全功能的磁碟機從一個儲存陣列移至另一個儲存陣列、則必須將適當的安全金鑰匯入新的儲存陣列。匯入金鑰會解除鎖定磁碟機上的資料。

.開始之前
* 目標儲存陣列（您要移動磁碟機的位置）必須已設定安全金鑰。移轉的磁碟機將重新輸入目標儲存陣列。
* 您必須知道要解除鎖定之磁碟機的相關安全性金鑰。
* 安全金鑰檔案可在管理用戶端上使用（使用瀏覽器存取System Manager的系統）。如果您要將磁碟機移至由不同系統管理的儲存陣列、則必須將安全金鑰檔案移至該管理用戶端。


.關於這項工作
本工作說明如何解除鎖定已從儲存陣列移除並重新安裝至其他磁碟機的安全磁碟機中的資料。陣列發現磁碟機後、會出現「Needs Attention（需要注意）」條件、並顯示這些重新定位磁碟機的「Security Key Needs（需要安全金鑰）」狀態。您可以將磁碟機資料的安全金鑰匯入儲存陣列、以解除鎖定磁碟機資料。在此過程中、您可以選取安全金鑰檔案、然後輸入金鑰的密碼。

[NOTE]
====
密碼與儲存陣列的管理員密碼不同。

====
如果新儲存陣列中安裝了其他已啟用安全功能的磁碟機、它們可能會使用與您匯入磁碟機不同的安全金鑰。在匯入程序期間、舊的安全金鑰僅用於解除鎖定您要安裝之磁碟機的資料。當解除鎖定程序成功時、新安裝的磁碟機會重新鎖定至目標儲存陣列的安全金鑰。

.步驟
. 選取功能表：設定[系統]。
. 在*安全金鑰管理*下、選取*解除鎖定安全磁碟機*。
+
「解除鎖定安全磁碟機」對話方塊隨即開啟。任何需要安全金鑰的磁碟機都會顯示在表格中。

. *選用：*將滑鼠移到磁碟機編號上方、即可查看磁碟機的位置（機櫃編號和機櫃編號）。
. 按一下*瀏覽*、然後選取與您要解除鎖定磁碟機對應的安全金鑰檔案。
+
您選取的金鑰檔會出現在對話方塊中。

. 輸入與此金鑰檔相關的密碼。
+
您輸入的字元會被遮罩。

. 按一下*解除鎖定*。
+
如果解除鎖定作業成功、對話方塊會顯示：「相關的安全磁碟機已解除鎖定。」



.結果
當所有磁碟機都已鎖定、然後解除鎖定時、儲存陣列中的每個控制器都會重新開機。但是、如果目標儲存陣列中已有未鎖定的磁碟機、則控制器將不會重新開機。
