---
permalink: sm-settings/use-ca-signed-certificates-for-controllers.html 
sidebar: sidebar 
keywords: ca signed certificate, secure communication, controller, browser, system manager 
summary: 您可以取得CA簽署的憑證、以便在控制器與瀏覽器之間進行安全通訊、以存取System Manager。 
---
= 控制器使用CA簽署的憑證
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以取得CA簽署的憑證、以便在控制器與瀏覽器之間進行安全通訊、以存取System Manager。

.開始之前
* 您必須以包含安全管理員權限的使用者設定檔登入。否則、不會顯示憑證功能。


使用CA簽署的憑證是三個步驟的程序。



== 步驟1：完成並提交控制器的CSR

您必須先為儲存陣列中的每個控制器產生憑證簽署要求（CSR）檔案、然後將檔案提交給憑證授權單位（CA）。

.開始之前
* 您必須知道每個控制器的IP位址或DNS名稱。


CSR提供組織、控制器IP位址或DNS名稱的相關資訊、以及識別控制器中Web伺服器的金鑰配對。在此工作期間、如果儲存陣列中只有一個控制器、則會產生一個CSR檔案、如果有兩個控制器、則會產生兩個CSR檔案。

[CAUTION]
====
提交至CA後、請勿產生新的CSR。產生CSR時、系統會建立私密與公開金鑰配對。公開金鑰是CSR的一部分、而私密金鑰則保留在金鑰庫中。當您收到簽署的憑證並將其匯入Keystore時、系統會確保私密金鑰和公開金鑰都是原始配對。因此、在將新的CSR提交給CA之後、您不得產生新的CSR。如果您這麼做、控制器就會產生新的金鑰、而且您從CA收到的憑證將無法運作。

====
.步驟
. 選取*功能表：設定[憑證]*。
. 從* Array Management（陣列管理）*選項卡中選擇*完整的csr*。
+
[NOTE]
====
如果看到對話方塊提示您接受第二個控制器的自我簽署憑證、請按一下*「接受自我簽署的憑證*」繼續。

====
. 輸入下列資訊、然後按一下*下一步*：
+
** *組織*：貴公司或組織的完整法定名稱。包括尾碼、例如Inc.或Corp.
** *組織單位（選用）*：您組織處理憑證的部門。
** *城市/地區*：儲存陣列或企業所在的城市。
** *州/地區（選用）*：儲存陣列或業務所在的州或地區。
** *國家ISO代碼*：您所在國家/地區的兩位數ISO（國際標準化組織）代碼、例如US。


+
[CAUTION]
====
某些欄位可能會預先填入適當的資訊、例如控制器的IP位址。除非您確定預先填入的值不正確、否則請勿變更。例如、如果您尚未完成CSR、則控制器IP位址會設為「'localhost.」 在此情況下、您必須將「'localhost'」變更為控制器的DNS名稱或IP位址。

====
. 驗證或輸入儲存陣列中控制器A的下列資訊：
+
** *控制器一般名稱*-預設會顯示控制器A的IP位址或DNS名稱。請確定此位址正確無誤、而且必須完全符合您輸入的內容、才能在瀏覽器中存取System Manager。
** *控制器備用IP位址*-如果通用名稱是IP位址、您可以選擇輸入控制器A的任何其他IP位址或別名對於多個項目、請使用以逗號分隔的格式。
** *控制器A備用DNS名稱*-如果通用名稱是DNS名稱、請為控制器A輸入任何其他DNS名稱對於多個項目、請使用以逗號分隔的格式。如果沒有替代DNS名稱、但您在第一個欄位中輸入DNS名稱、請在此處複製該名稱。如果儲存陣列只有一個控制器、則可使用* Finish（完成）*按鈕。如果儲存陣列有兩個控制器、則可使用* Next*按鈕。


+
[NOTE]
====
當您初次建立CSR要求時、請勿按一下*跳過此步驟*連結。此連結是在錯誤恢復情況下提供的。在極少數情況下、CSR要求可能會在一個控制器上失敗、但在另一個控制器上失敗。此連結可讓您跳過在控制器A上建立CSR要求的步驟（如果已定義）、然後繼續下一步、在控制器B上重新建立CSR要求

====
. 如果只有一個控制器、請按一下「*完成*」。如果有兩個控制器、請按「*下一步*」輸入控制器B的資訊（與上述相同）、然後按一下「*完成*」。
+
對於單一控制器、一個CSR檔案會下載到您的本機系統。對於雙控制器、會下載兩個CSR檔案。下載的資料夾位置取決於您的瀏覽器。

. 找到下載的CSR檔案。資料夾位置取決於您的瀏覽器。
. 將CSR檔案提交給CA、並以PEEM格式要求簽署的憑證。
. 等待CA傳回憑證、然後前往  2: Import signed certificates for controllers。




== 步驟2：匯入控制器的簽署憑證

收到簽署的憑證之後、您會匯入控制器的檔案。

.開始之前
* CA傳回簽署的憑證檔案。
* 這些檔案可在您的本機系統上使用。
* 如果CA提供鏈結的憑證（例如.p7b檔案）、您必須將鏈結的檔案解壓縮至個別檔案：根憑證、一或多個中繼憑證、以及識別控制器的伺服器憑證。您可以使用Windows「certmgr」公用程式來解壓縮檔案（按一下滑鼠右鍵並選取*功能表：All Tasks（所有工作）[Export（匯出）]*）。匯出完成後、會針對鏈中的每個憑證檔案顯示一個CER.檔案。


本工作說明如何上傳憑證檔案。

.步驟
. 選取*功能表：設定[憑證]*。
. 從* Array Management（陣列管理）*選項卡中選擇* Import（*匯入）*。
+
隨即開啟一個對話方塊、用於匯入憑證檔案。

. 按一下*瀏覽*按鈕、先選取根和中繼檔案、然後選取控制器的每個伺服器憑證。兩個控制器的根和中間檔案相同。每個控制器只有伺服器憑證是唯一的。
+
檔案名稱會顯示在對話方塊中。

. 按一下*匯入*。
+
檔案已上傳並驗證。



工作階段會自動終止。您必須再次登入、憑證才能生效。當您再次登入時、新的CA簽署憑證會用於您的工作階段。
