---
permalink: um-certificates/use-ca-signed-certificate-um.html 
sidebar: sidebar 
keywords: ca certificate, secure, access, management, system, unified manager 
summary: 您可以取得及匯入CA簽署的憑證、以安全存取裝載Unified Manager的管理系統。 
---
= 使用CA簽署的憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以取得及匯入CA簽署的憑證、以安全存取裝載Unified Manager的管理系統。

.開始之前
* 您必須以包含安全管理員權限的使用者設定檔登入。否則、不會顯示憑證功能。


.關於這項工作
使用CA簽署的憑證是兩個步驟的程序。



== 步驟1：完成並提交CSR

您必須先產生憑證簽署要求（CSR）檔案、然後將其傳送至CA。

.開始之前
* 您必須以包含安全管理員權限的使用者設定檔登入。否則、不會顯示憑證功能。


.關於這項工作
本工作說明如何產生您傳送給CA的CSR檔案、以接收裝載Unified Manager和Web Services Proxy之系統的已簽署管理憑證。您必須提供組織的相關資訊、以及主機系統的IP位址或DNS名稱。

[CAUTION]
====
提交至CA後、請勿產生新的CSR。產生CSR時、系統會建立私密與公開金鑰配對。公開金鑰是CSR的一部分、而私密金鑰則保留在金鑰庫中。當您收到簽署的憑證並將其匯入Keystore時、系統會確保私密金鑰和公開金鑰都是原始配對。因此、在將新的CSR提交給CA之後、您不得產生新的CSR。如果您這麼做、控制器就會產生新的金鑰、而且您從CA收到的憑證將無法運作。

====
.步驟
. 選擇*憑證管理*。
. 從*管理*索引標籤、選取*完整的csr*。
. 輸入下列資訊、然後按一下*下一步*：
+
** *組織*：貴公司或組織的完整法定名稱。包括尾碼、例如Inc.或Corp.
** *組織單位（選用）*：您組織處理憑證的部門。
** *城市/地區*：您的主機系統或企業所在的城市。
** *州/地區（選用）*：主機系統或企業所在的州或地區。
** *國家ISO代碼*：您所在國家/地區的兩位數ISO（國際標準化組織）代碼、例如US。


. 輸入主機系統的下列相關資訊：
+
** *一般名稱*：安裝Web服務Proxy之主機系統的IP位址或DNS名稱。請確定此位址正確無誤、而且必須完全符合您輸入的內容、才能在瀏覽器中存取Unified Manager。請勿包含http：//或https：//。
** *備用IP位址*-如果一般名稱是IP位址、您可以選擇輸入主機系統的任何其他IP位址或別名。對於多個項目、請使用以逗號分隔的格式。
** *備用DNS名稱*-如果通用名稱是DNS名稱、請輸入主機系統的任何其他DNS名稱。對於多個項目、請使用以逗號分隔的格式。如果沒有替代DNS名稱、但您在第一個欄位中輸入DNS名稱、請在此處複製該名稱。


. 單擊*完成*。
+
CSR檔案會下載至您的本機系統。下載的資料夾位置取決於您的瀏覽器。

. 將CSR檔案提交給CA、並以PEEM或DER格式要求簽署的憑證。


.完成後
等待CA傳回憑證檔案、然後前往 link:step-3-import-management-certificates-unified.html["步驟2：匯入管理憑證"]。



== 步驟2：匯入管理憑證

收到簽署的憑證後、請匯入安裝Unified Manager介面的主機系統的憑證鏈結。

.開始之前
* 您必須以包含安全管理員權限的使用者設定檔登入。否則、不會顯示憑證功能。
* 您已產生憑證簽署要求（.CSR檔案）、並將其傳送至CA。
* CA傳回信任的憑證檔案。
* 憑證檔案會安裝在您的本機系統上。
* 如果CA提供鏈結的憑證（例如.p7b檔案）、您必須將鏈結的檔案解壓縮至個別檔案：根憑證、一或多個中繼憑證及伺服器憑證。您可以使用Windows「certmgr」公用程式來解壓縮檔案（按一下滑鼠右鍵並選取*功能表：All Tasks（所有工作）[Export（匯出）]*）。匯出完成後、會針對鏈中的每個憑證檔案顯示一個CER.檔案。


.步驟
. 選擇*憑證管理*。
. 從*管理*索引標籤、選取*匯入*。
+
隨即開啟一個對話方塊、用於匯入憑證檔案。

. 按一下*瀏覽*以先選取根和中繼檔案、然後選取伺服器憑證。
+
檔案名稱會顯示在對話方塊中。

. 按一下*匯入*。


.結果
檔案會上傳並驗證。憑證資訊會顯示在「憑證管理」頁面上。
